### ISSUE TITLE
SecondaryType aspect deletion affects access to document

### ISSUE THREAD

**Issue by fabriceNanni** [johanlelan/lightweightCMISserver#1]
Johan, 
An exception occurs when accessing a document with custom properties when the aspect has been dropped from the server.

Reproduction :
.Create a new aspect on SecondaryType.
.Add this secondary type  to a document.
.Add value to aspect properties for this document
.Delete the newly added aspect.

=> Exception occurs when reading the content of the document folder (in workbench ).
=> Idem with a REST request
=> Cannot delete the document via a REST request.

**Comment by johanlelan** [comment]
no return. So consider it close
