### ISSUE TITLE
Error 500 when moving file to a folder 

### ISSUE THREAD

**Issue by fabriceNanni** [johanlelan/lightweightCMISserver#2]
When moving a file to a folder that already contains the same filename, we get the following error 500:

{
"exception": "runtime",
"message": null,
"stacktrace": "org.apache.chemistry.opencmis.commons.exceptions.CmisRuntimeException\ \	at org.apache.chemistry.opencmis.server.shared.Dispatcher.dispatch(Dispatcher.java:100)\ \	at org.apache.chemistry.opencmis.server.impl.browser.CmisBrowserBindingServlet.dispatch(CmisBrowserBindingServlet.java:364)\ \ at org.apache.chemistry.opencmis.server.impl.browser.CmisBrowserBindingServlet.service(CmisBrowserBindingServlet.java:239)\ \	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)\ \	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)\ \	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\ \	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)\ \	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)\ \	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)\ \	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)\ \	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)\ \	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)\ \	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)\ \	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)\ \	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)\ \	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)\ \	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)\ \	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)\ \	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)\ \	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)\ \	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\ \	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\ \	at java.lang.Thread.run(Thread.java:745)\ Caused by: java.lang.IllegalMonitorStateException\ \	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:155)\ \	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1260)\ \	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:460)\ \	at org.apache.chemistry.opencmis.inmemory.storedobj.impl.ObjectStoreImpl.unlock(ObjectStoreImpl.java:165)\ \	at org.apache.chemistry.opencmis.inmemory.storedobj.impl.ObjectStoreImpl.move(ObjectStoreImpl.java:814)\ \	at org.apache.chemistry.opencmis.inmemory.server.InMemoryObjectServiceImpl.moveObject(InMemoryObjectServiceImpl.java:544)\ \ at org.apache.chemistry.opencmis.inmemory.server.InMemoryService.moveObject(InMemoryService.java:310)\ \	at org.apache.chemistry.opencmis.server.impl.browser.ObjectService$MoveObject.serve(ObjectService.java:1083)\ \	at org.apache.chemistry.opencmis.server.shared.Dispatcher.dispatch(Dispatcher.java:92)\ \	... 22 more\ "
}

**Comment by johanlelan** [comment]
fix in last commit
